inherit_from: .rubocop_rspec.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  # The IgnoreCopDirectives option causes the LineLength rule to ignore cop
  # directives like '# rubocop: enable ...' when calculating a line's length.
  IgnoreCopDirectives: true

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - spec/**/*.rb

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  CountAsOne:
    - hash
    - array
    - heredoc