require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  # The IgnoreCopDirectives option causes the LineLength rule to ignore cop
  # directives like '# rubocop: enable ...' when calculating a line's length.
  IgnoreCopDirectives: true
